spring:
  application:
    name: library-service
  datasource:
    url: jdbc:mysql://localhost:3309/libraries
    username: root
    password: my-secret-pw
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8090
